apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dp
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
       app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
       app: grafana
    spec:
      containers:
      - image: akshayab99/grafana-os:v1
        name: grafana
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: grafana-pvc
          mountPath: /var/lib/grafana/
      volumes:
      - name: grafana-pvc
        persistentVolumeClaim:
          claimName: grafana-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
     app: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30306
  selector:
    app: grafana
  type: NodePort
  