apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-dp
  labels:
    app: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
      - image: akshayab99/prometheus-os:v1
        name: prom
        ports:
        - containerPort: 9090
          name: prom
        volumeMounts:
        - name: prom-vol
          mountPath: /prometheus/data
        - name: prom-configmap
          mountPath: /prometheus-2.19.0.linux-amd64/prometheus.yml
          subPath: prometheus.yml
      volumes:
        - name: prom-configmap
          configMap:
            name: prom-configmap
        - name: prom-vol
          persistentVolumeClaim:
            claimName: prom-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: prom-svc
  labels:
    app: prom
spec:
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30303
  selector:
    app: prom
  type: NodePort
