apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-configmap
  labels:
    app: prom-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval:     20s 
      evaluation_interval: 20s 
    scrape_configs:
     - job_name: 'prometheus'
       static_configs:
        - targets: ['localhost:9090']
        
     - job_name: 'rhelnode1'
       static_configs:
        - targets: ['192.168.1.26:9100']
---       

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: prom-pvc
  labels:
    name: prom-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi